---
version: "2.1"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gosec
    - bodyclose
    - whitespace
    - unused

linters-settings:
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: var-naming
        arguments: [["ID", "URL", "HTTP", "API"]]
